version: '3.1'
services:
  ms:
    image: easy-notes
    container_name: easy-notes
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    container_name: mysql-note
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_app
    ports:
     - 42333:3306